# Template taken from: https://github.com/Mtze/kubernetes-templates/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.article_fetcher.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.article_fetcher.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.article_fetcher.name }}
    spec:
      containers:
        - name: {{ .Values.service.article_fetcher.name }}
          image: "{{.Values.base_imagedomain}}{{ .Values.service.article_fetcher.image_name }}:{{ .Values.release }}"
          imagePullPolicy: {{ .Values.service.article_fetcher.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.article_fetcher.port }}
              name: {{ .Values.service.article_fetcher.name }}
