# Template taken from: https://github.com/Mtze/kubernetes-templates/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.topic_discovery.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.topic_discovery.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.topic_discovery.name }}
    spec:
      containers:
        - name: {{ .Values.service.topic_discovery.name }}
          image: "{{.Values.base_imagedomain}}{{ .Values.service.topic_discovery.image_name }}:{{ .Values.release }}"
          imagePullPolicy: {{ .Values.service.topic_discovery.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.topic_discovery.port }}
              name: {{ .Values.service.topic_discovery.name }}
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api_secrets.name }}
                  key: {{ .Values.api_secrets.GOOGLE_API_KEY }}
            - name: GENAI_BASE_URL
              value: {{ .Values.service.api.env.GENAI_BASE_URL | quote }}

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
